site_name: Race statistics
site_url: https://mika-s.github.io/race-statistics/

theme:
  name: material
  custom_dir: overrides
extra:
  analytics:
    provider: google
    property: G-TWHSR70SC3
extra_css:
  - assets/stylesheets/extra.css
